TheKevJames/coveralls-python

- coveralls/api.py
- tests/test_api.py
Allow merging of coverage data in python3 as well as python2. (Fixed failure to load json coverage file in python3.)
This fixes issue #56
> Allow merging of coverage data in python3 as well as python2.

- coveralls/api.py
- coveralls/cli.py
- tests/test_cli.py
Allow debug and output options to work without repo_token, as it is not needed for these options.
Fixes #45
> Allow debug and output options to work without repo_token.

- README.rst
- coveralls/api.py
- tests/test_api.py
I had a bit of difficulty figuring out how to use mocha with coveralls. Mocha has its own JSON output, but it is not compatible with coveralls and so the merge silently failed. I had to debug to figure out what was going on. I've added a mocha example to the documentation about merging in external data, and a warning log message if data cannot be merged, so hopefully others will find this painless in future.
> Added more explanation around merging.

- coveralls/api.py
- coveralls/reporter.py
- tests/test_api.py
Make coveralls work with released versions of coverage and django-coverage-plugin. Right now, it only works with the tip of my github repo for django-coverage-plugin, which is not ideal. With the released versions of coverage, django-coverage-plugin, and coveralls, you get:
```
Traceback (most recent call last):
File "/Users/jessamyn/.virtualenvs/eggtimer/bin/coveralls", line 11, in <module>
sys.exit(main())
File "/Users/jessamyn/.virtualenvs/eggtimer/lib/python3.4/site-packages/coveralls/cli.py", line 55, in main
coverallz.wear(dry_run=True)
File "/Users/jessamyn/.virtualenvs/eggtimer/lib/python3.4/site-packages/coveralls/api.py", line 82, in wear
json_string = self.create_report()
File "/Users/jessamyn/.virtualenvs/eggtimer/lib/python3.4/site-packages/coveralls/api.py", line 101, in …
```
> Make coveralls work with released versions of coverage packages

- coveralls/api.py
Right now Codeship builds just go onto the HEAD branch, which isn't super useful. This should pull the branch of Codeship builds so that they're appropriately marked in Coveralls. [Reference](https://codeship.com/documentation/continuous-integration/set-environment-variables/#default-environment-variables)
> Pull branch from Codeship environment

- coveralls/cli.py
- tests/test_cli.py
I am using coveralls in a build script, and I'd like to know if any step fails. If coveralls returns a non-zero exit status in case of failure, then all works as expected.
> Return an exit status if coveralls fails

- coveralls/api.py
- tests/test_api.py
Recently I added Windows support, AppVeyor CI tests and coverage collection on Windows to a project of mine (see paylogic/pip-accel#61). In the process I found that support for AppVeyor in *coveralls-python* was a bit tricky to get right.
The `$CI_BRANCH` environment variable isn't available on AppVeyor and the `git rev-parse --abbrev-ref HEAD` fallback in *coveralls-python* incorrectly resulted in `HEAD` which meant my coverage reports on Coveralls.io referenced the branch name `HEAD` instead of the expected value `master` (kind of confusing because `HEAD` isn't a branch AFAIK :-).
During experimentation I worked around this by [creating a wrapper](https://github.com/paylogic/pip-accel/blob/9b4d0186886c0585a7357665933908adfad9f1d5/scripts/appveyor-coverage.py) for the `coveralls` command …
> Improve support for AppVeyor CI

- coveralls/api.py
- tests/test_api.py
This pull request adds support for the BuildKite CI system, allowing the library to pick up the BuildKite job ID, and the branch that it was built against.
Added a test for this also.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/coagulant/coveralls-python/112)
> Add Buildkite support

- coveralls/api.py
- tests/test_api.py
Mentioning the alternative of setting an environment variable is more useful for CI contexts.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/coagulant/coveralls-python/111)
> Improve error message for missing Coveralls token.

- .travis.yml
- tox.ini
- Drop Python 2.6. Builds failed on Travis under 2.6 due to an
InsecurePlatformWarning. SSL is insecure on vanilla Python
versions before 2.7.9 as mentioned in [urllib3's docs][1].
- Replace pypy (2.5.0) with pypy-5.4. This was failing due to the
same issue as python2.6. Pypy 2.5.0 is based on Python 2.7.8 in
Travis, while Pypy 5.4.0 is based on Python 2.7.10.
- Replace pypy3 (2.4.0) with pypy3.3-5.2-alpha1. Failures here were
related to incompatibility between setuptools and Python 3.2. See
more details on [the related Travis issue][2].
[1]: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
[2]: https://github.com/travis-ci/travis-ci/issues/6277
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …
> Fix Travis runtime versions

- coveralls/reporter.py
- example/project.py
- example/runtests.py
- tests/test_api.py
Since coverage.io does not currently support branch coverage separately, I would like to mark those lines with only partial branch coverage as not covered.
If branch coverage is collected, this marks partially covered lines as not covered. If this implicit approach is not preferred, I could add an option for enabling this.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/coagulant/coveralls-python/121)
> Report partially covered branches as not covered

- .gitignore
- README.rst
- setup.cfg
- setup.py
- tests/test_cli.py
- tox.ini
Fixes #139 
Forced an install of the latest pytest (3.0.6) and found no errors. We should wait until CI works again before merging this, just to be sure.
> chore(dependencies): unpin pytest version, use pytest-runner

- coveralls/reporter.py
- tests/test_api.py
- tox.ini
Fixes #143 
This changes branch coverage reporting to use the new branches field of the coveralls API.
> Use coveralls' new branch reporting format

- .travis.yml
- coveralls/reporter.py
- tox.ini
This is based on cclauss' pull request #146 but with changes on top to:
1. Cope with broken versions of coverage.py on Python 3.6. Branch coverage is merely disabled, the rest should work.
2. Skip the tests which fail under these old versions, because it is not a bug in coveralls-python.
> Python 3.6 support and testing

- coveralls/api.py
- docs/usage/tox.rst
- tests/api/configuration_test.py
add logic to parse `CI_PULL_REQUEST` env variable. 
Currently this variable is not parsed for jenkins configuration.  
https://coveralls.zendesk.com/hc/en-us/articles/201347419-Coveralls-currently-supports `JENKINS PULL REQUEST SUPPORT` section suggest to use it in conjunction with github pull request builder config
> feat(jenkins): add logic to parse CI_PULL_REQUEST env variable

- coveralls/api.py
Tries to fix #174
Alternatively, we could require a flag or take the test out of the `git_info` method although it seems fitting imo.
> Silently omit git argument when git is unavailable

- README.rst
The previous one produces a "Permission Denied" page for me.
> Fix links to readthedocs

- coveralls/api.py
This PR adds support for a beta feature we are releasing soon on Coveralls which allows you to provide a flag name for jobs. 
Jobs with flag names will send additional GitHub statuses so you can track and know how coverage changed in separate areas whether that is unit/integration/E2E tests or backend/frontend.
> Adds ability to add named job

- coveralls/git.py
Addresses this comment: https://github.com/coveralls-clients/coveralls-python/issues/174#issuecomment-420686421
Previously, git info was omitted if git was installed but the .git directory was missing.
This fix will also omit git info in case git itself is missing (unless, of course, the environment args are there).
> feat(git): Omit git info when git isnt installed

- coveralls/api.py
- coveralls/git.py
- docs/usage/tox.rst
- tests/api/configuration_test.py
Added support for SemaphoreCI by parsing corresponding environment variables.
To avoid `pylint` failure:
```
R:103, 4: Too many return statements (7/6) (too-many-return-statements)
```
I changed the behavior of `load_config_from_ci_environment` to return only once in the end.
> SemaphoreCI support

- coveralls/api.py
- tests/api/configuration_test.py
https://buildkite.com/docs/pipelines/environment-variables says that
the pull request is available via BUILDKITE_PULL_REQUEST, which is
either the number for a pull request, or "false" for a
non-pull-request.
> feat(api): support pull requests on buildkite

- setup.py
This PR unpins urllib3 and effectively reverts #200. As per psf/requests#5067, requests now works with urlib3 v1.25.
> Unpin urllib3

- coveralls/reporter.py
Fixes two bugs:
* __version__ is type str; pypy3 throws exception comparing str with int
* __version__[1] == '.', not the minor version number
> Fix coverage.__version__ comparisons

- coveralls/api.py
- coveralls/git.py
- docs/usage/configuration.rst
- docs/usage/tox.rst
- tests/api/configuration_test.py
- tests/git_test.py
This adds support for CI running on [github actions](https://help.github.com/en/actions).
Getting the branch name is a little more tricky since the default way of repository cloning with actions/checkout puts you in a detached HEAD in which the regular `git rev-parse --abbrev-ref HEAD` returns _HEAD_ instead of the branch name.
> Support github actions CI

- coveralls/api.py
- docs/usage/configuration.rst
- docs/usage/tox.rst
- tests/api/configuration_test.py
- tests/git_test.py
The coveralls API refuses to accept submissions with service=github, but accepts
submissions with service=github-actions.
> fix(github): rename service to github-actions

- .circleci/config.yml
- coveralls/api.py
- coveralls/reporter.py
- setup.py
- tox.ini
I can't say I'm excited about this code, but at the very least this should be fully backwards compatible with how `coverage<5` + `coveralls` work together. There's definitely going to need to be some future work to clean this up, but hopefully this should be enough to get folks unblocked from using `coverage>=5.0`.
> feat: support coverage>=5.0

- docs/index.rst
Spotted while looking into #203. I see other parts of the documentation (https://coveralls-python.readthedocs.io/en/latest/tips/coveragerc.html) already link to the `latest` version, hence why I propose to link to it here as well.
> Update broken link to coverage.py docs

- .pre-commit-config.yaml
- coveralls/api.py
- setup.py
- tests/api/configuration_test.py
- tests/api/encoding_test.py
- tests/api/reporter_test.py
- tests/api/wear_test.py
- tests/git_test.py
- tox.ini
Looks like PyPy2 and `sh` don't play nicely together -- bye bye `sh`!
Also seems like PyYAML has removed support for Py3.4. That's not unreasonable at all, but I'm going to continue supporting it for now, until a decent reason to avoid that. PyYAML's v5.3 release seems to be mostly stylistic in terms of its impact on us, so I'll stick with it for now.
> fix version incompatibilites

- .circleci/config.yml
- .github/workflows/pythonpackage.yml
- .gitignore
- .pre-commit-config.yaml
- .travis.yml
- README.rst
- coveralls/__init__.py
- coveralls/api.py
- coveralls/cli.py
- coveralls/git.py
- coveralls/reporter.py
- docs/conf.py
- docs/usage/tox.rst
- example/__init__.py
- example/project.py
- example/runtests.py
- nonunicode/__init__.py
- setup.py
- tests/__init__.py
- tests/api/__init__.py
- tests/api/configuration_test.py
- tests/api/encoding_test.py
- tests/api/reporter_test.py
- tests/api/wear_test.py
- tests/api_test.py
- tests/cli_test.py
- tests/conftest.py
- tests/git_test.py
- tox.ini
I think it's about time to remove support for these -- they've started to cause compatibility issues with libraries and are making this code hard to maintain. We can release this as a major version bump and any users in outdated environments can simply continue to use `coveralls<2.0`.
Nukes support for:
* Python 2.7 and 3.4
* Coverage 3.x and 4.0.x
Also cleans up a whole bunch of no-longer-necessary code and makes it a bit easier to add tests for pre-alpha things (eg. Py39).
> chore: remove support for deprecated things

- coveralls/api.py
- coveralls/cli.py
- coveralls/exception.py
- docs/usage/configuration.rst
- docs/usage/tox.rst
- setup.py
- tests/api/configuration_test.py
- tests/cli_test.py
- tox.ini
Github Actions, and the coveralls side of support for it, seem to have changed/evolved.
This PR brings coveralls-python in line with the official github action, which is commonly used to finish parallel builds.
Additionally, there is no need to manually provide your repo token anymore (though you still can, so existing setups should not be affected by this), since the native github support takes the automatically provided GITHUB_TOKEN instead, very similar to how things work on Travis.
You do however have to export that GITHUB_TOKEN to an env var in your workflow.yml:
```
env:
GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
> Update Github Actions support

- coveralls/exception.py
- tests/api/exception_test.py
Fixes https://github.com/coveralls-clients/coveralls-python/issues/229
> Fix unhashable exception

- coveralls/api.py
I *think* CIRCLE_WORKFLOW_ID maps to the `number` variable (aka [service_number](https://docs.coveralls.io/api-reference)) but I'm not 100% sure.
Note that node coveralls uses CIRCLE_WORKFLOW_ID as the service number. See https://github.com/nickmerwin/node-coveralls/blob/705c3b5963e3cc76f8e70381dbae20979008c9b8/lib/getOptions.js#L66
> add service number

- docs/usage/tox.rst
Looks like the buildkite environment variable was mistyped (missing an e)
> Fix typo in Tox docs

- coveralls/api.py
As the commit/other information doesn't change when performing a
rebuild, resubmissions will fail with an HTTP 422 error. This adds a
workaround for such cases, appending a random value to the id and
attempting a resubmission with that.
> Add workaround allowing resubmission

- docs/usage/configuration.rst
Addresses https://github.com/coveralls-clients/coveralls-python/issues/243
> Docs: Fixes on COVERALLS_FLAG_NAME and COVERALLS_REPO_TOKEN for GitHub Actions

- coveralls/api.py
- docs/usage/configuration.rst
- tests/api/configuration_test.py
> feat(config): reorder configuration precedence

- CHANGELOG.md
Use the one provided by `coveralls --help` which actually works.
> Fix option name

- coveralls/api.py
If a submission is failed, the tool will check and adjust/resubmit again with a newly generated job_id. For GitHub Actions, this needs to be null again.
https://github.com/TheKevJames/coveralls-python/issues/252#issuecomment-783452375
> fix(github): send null job_id to fix 422 during resubmission

- coveralls/git.py
- tests/git_test.py
Modify the logic of getting the branch information to also be able to parse out the tag name when dealing with a tag push event on Github Actions.
> Push github actions coverage information from tags

- tests/git_test.py
This PR adds a test to cover the folder is not a git repository corner case.
The only motive was to increase the coverage.
```
coveralls/git.py            36      0     10      0   100%
```
:partying_face:
> tests(git): add test to cover not a git repository case

- coveralls/api.py
- docs/usage/configuration.rst
- tests/api/configuration_test.py
This PR is related to #299 and #256.
The official docs for Coveralls define a set of generic environment variables that once defined should support any CI environment: https://docs.coveralls.io/supported-ci-services (bottom of the page).
The changes implemented in this PR attempt to read those variables but allows the values to be overwritten by any CI-specific configuration currently supported. They were also inspired by the official client ([coveralls-ruby - lib/coveralls/configuration.rb -set_standard_service_params_for_generic_ci](https://github.com/lemurheavy/coveralls-ruby/blob/76bbd5f930ab66f4f9e85970c3ec46510072086d/lib/coveralls/configuration.rb#L116)).
On top of the automated tox and pre-commit, I also did a manual test (to make sure no coveralls API error was introduced) …
> feat(api): support officially documented generic CI env vars (#299)

- coveralls/api.py
- coveralls/cli.py
- coveralls/reporter.py
- tests/api/reporter_test.py
- tests/cli_test.py
When the repository of Python project on GitHub has the structure
```
/myproject
/src
/myproject
__init__.py
somefile.py
/docs
...
/tests
...
README.md
tox.ini
...
```
and CI runs `tox` where `tox.ini` has set `usedevelop = false` and it runs tests with `pytest --cov=myproject --cov-report=term-missing tests`, where `myproject` refers to `myproject` package build and installed by `tox`, the coverage report will look like this:
```
----------- coverage: platform linux, python 3.6.8-final-0 -----------
Name                                                          Stmts   Miss  Cover   Missing
------------------------------------------------------------------------------------------------
.tox/py36/lib/python3.6/site-packages/myproject/__init__.py       1      0   100% …
```
> feat: add --srcdir option

- docs/usage/configuration.rst
The GITHUB_TOKEN in this example _should_ of course be just a read-only token but in any case secrets should not be exposed to code that does not need them. In this case pip does not need to authenticate to GitHub.
> docs/configuration: Avoid over-exposing GITHUB_TOKEN

- coveralls/api.py
Fixes the mapping between default (eg. `COVERALLS_*`) env vars and the
equivalent config values, which had some mismatches for job
identification cases.
Fixes #303
> fix(env): fixup handling of default env service values

- coveralls/reporter.py
- setup.py
- tests/coverage_templates/bar.py
- tests/coverage_templates/bar_310.py
- tests/coverage_templates/foo.py
- tests/integration_test.py
- tox.ini
There aren't really any issues with the current version.
Verified by providing a smoke integration test
Updated tox and classifiers
fixes #326
> Add support for coverage 6.x

- setup.py
Closes #333
Due to a backwards incompatible change in `coverage`, there is an incompatibility with versions `6.0` - `6.1.1`.
Additional details: https://github.com/nedbat/coveragepy/issues/1273
> Exclude incompatible coverage versions

- coveralls/api.py
- docs/usage/tox.rst
- tests/api/configuration_test.py
Support for parallel execution with CircleCI does not function as expected. With 16 parallel execution nodes followed by the parallel-complete webhook, the following result is seen on the Coveralls dashboard. Note the `.16` at the end, indicating that only the final node's coverage report was processed correctly.
This PR makes a minor change to utilize the `CIRCLE_NODE_INDEX`, which is required for parallel execution support. This change mirrors the functionality from [coveralls-ruby](https://github.com/lemurheavy/coveralls-ruby/blob/6453624810be9862842874f0c812c7af45c5cadb/lib/coveralls/configuration.rb#L61).
Utilizing e26d574388db8e83dd93d6c84e6a79243a8b1d3f, subsequent runs yielded the expected results on the Coveralls dashboard.
> Fix support for parallel execution on CircleCI

- coveralls/reporter.py
- tests/api/reporter_test.py
Introduces a breaking change:
When `config.ignore_errors` is Falsey, failures to parse Python files or
look up file source will now interrupt and early exit collection.
Previously, these were either manually muted or only errored after
collecting _all_ failures.
> refactor(coverage): use more of the coverage public interface

- docs/usage/tox.rst
tox4 no longer allows space-separated `passenv`
https://github.com/tox-dev/tox/issues/2615
however tox3 doesn't support `VAR, ` either
so to support both versions of tox, use this funky space + comma separated syntax, which really does work.
> tox.rst: update passenv examples for tox3 and tox4

- coveralls/api.py
- docs/usage/configuration.rst
- tests/api/configuration_test.py
> fix(gha): s/github-actions/github/

- tests/git_test.py
> test(git): support running tests outside of gitdir
